name             'fiddler'
maintainer       'me'
maintainer_email 'me@example.com'
license          'Apache 2'
description      'Installs Fiddler'
long_description 'Installs Fiddler, a HTTP debugging tool'
version          '0.1.0'
supports         'windows'
depends          'windows'
